"""Markdown rendering — turn Consensus + ProviderReviews into a PR comment.

Layout:
  1. Status header (✅/⚠️ per provider)
  2. Consensus block (groups where reviewers agreed)
  3. Disagreements (groups where severity differed)
  4. Per-model details (collapsed <details>)

Failure-tolerant by design — even if every reviewer failed, we still post
something so the Action visibly worked.
"""

from __future__ import annotations

from chorus.models import Consensus, FindingGroup, ProviderReview, Severity

SEVERITY_EMOJI: dict[Severity, str] = {
    "critical": "🔴",
    "major": "🟠",
    "minor": "🟡",
    "nit": "🔵",
}

STATUS_EMOJI = {"ok": "✅", "skipped": "⚠️", "failed": "⚠️", "timeout": "⏱️"}


def _status_line(r: ProviderReview) -> str:
    emoji = STATUS_EMOJI.get(r.status, "❓")
    label = f"{emoji} **{r.provider}** ({r.model})"
    if r.status == "ok":
        n = len(r.findings)
        return f"{label} — {n} finding{'s' if n != 1 else ''}"
    if r.status == "skipped":
        return f"{label} — skipped: {r.error or 'no API key'}"
    if r.status == "timeout":
        return f"{label} — timeout"
    return f"{label} — failed: {r.error or 'unknown error'}"


def _render_finding(f, *, show_provider: str | None = None) -> str:
    head = f"{SEVERITY_EMOJI[f.severity]} **{f.severity.upper()}** · `{f.file}"
    if f.line is not None:
        head += f":{f.line}"
    head += "`"
    if show_provider:
        head += f" · _{show_provider}_"
    return f"{head}\n\n**{f.title}**\n\n{f.description}\n"


def _render_group(g: FindingGroup) -> str:
    providers = ", ".join(g.providers)
    head = (
        f"{SEVERITY_EMOJI[g.severity]} **{g.severity.upper()}** · `{g.file}` · "
        f"raised by {providers}\n\n**{g.title}**\n"
    )
    bodies = []
    for f in g.findings:
        loc = f":L{f.line}" if f.line is not None else ""
        bodies.append(f"- _{loc} (conf {f.confidence:.2f})_ {f.description}")
    return head + "\n".join(bodies) + "\n"


def render(consensus: Consensus, reviews: list[ProviderReview]) -> str:
    parts: list[str] = []

    parts.append("## 🎵 ai-chorus review\n")

    # 1. Status header
    parts.append("### Reviewers\n")
    for r in reviews:
        parts.append(f"- {_status_line(r)}")
    parts.append("")

    if consensus.total_reviews_ok == 0:
        parts.append(
            "_All reviewers failed or were skipped. See above for details. "
            "Configure API keys in repo secrets to enable reviews._"
        )
        return "\n".join(parts)

    # 2. Consensus
    consensus_groups = [g for g in consensus.groups if g.classification == "consensus"]
    if consensus_groups:
        parts.append(f"### 🤝 Consensus findings ({len(consensus_groups)})\n")
        parts.append("_Multiple reviewers flagged these — high signal._\n")
        for g in consensus_groups:
            parts.append(_render_group(g))

    # 3. Disagreements
    disagreement_groups = [g for g in consensus.groups if g.classification == "disagreement"]
    if disagreement_groups:
        parts.append(f"### ⚖️ Disagreements ({len(disagreement_groups)})\n")
        parts.append("_Reviewers raised the same issue but disagree on severity._\n")
        for g in disagreement_groups:
            parts.append(_render_group(g))

    # 4. Unique findings — collapsed
    unique_groups = [g for g in consensus.groups if g.classification == "unique"]
    if unique_groups:
        parts.append(f"<details>\n<summary><b>🔍 Unique findings ({len(unique_groups)})</b> — "
                     "only one reviewer raised, needs human judgment</summary>\n")
        for g in unique_groups:
            parts.append(_render_group(g))
        parts.append("</details>\n")

    # 5. Per-model details (raw outputs)
    parts.append("<details>\n<summary><b>Per-model raw output</b></summary>\n")
    for r in reviews:
        if r.status != "ok":
            continue
        parts.append(f"#### {r.provider} ({r.model})\n")
        if r.summary:
            parts.append(f"_{r.summary}_\n")
        if not r.findings:
            parts.append("_No findings._\n")
        for f in r.findings:
            parts.append(_render_finding(f))
    parts.append("</details>\n")

    parts.append(
        "---\n_Generated by [ai-chorus](https://github.com/ArLeyar/ai-chorus) — "
        "vendor-agnostic multi-model PR review._"
    )

    return "\n".join(parts)
